#!/usr/bin/env python3
"""Check production stock-audio capture with the real SePcm and OEM extractor."""
import os
from pathlib import Path
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
java_home = Path(os.environ.get('JAVA_HOME', '/usr/lib/jvm/java-26-openjdk'))
source = (root / 'src/com/stand/bridge/RuBridge.java').read_text()
oem = Path(os.environ.get('E07_OEM_CONVERTER', root / 'out/oem/sources/com/iflytek/speech/se/PcmConvertor.java'))


def extract(signature):
    start = source.index('    ' + signature)
    return source[start:source.index('\n    }', start) + len('\n    }')]


capture = '\n'.join(extract(signature) for signature in (
    'private static final class StockFrame {',
    'private static final class RuSession {',
    'public static boolean acceptStockFrame(',
    'public static boolean startSession(',
    'public static void stopSession(',
    'private static void recordSession(',
))
assert 'AudioRecord' not in capture and 'AudioPolicy' not in capture
files = {
    'android/content/Context.java': r'''
package android.content;
public class Context {
    public static final String AUDIO_SERVICE = "audio";
    public Object getSystemService(String name) { return new android.media.AudioManager(); }
}
''',
    'android/media/AudioManager.java': r'''
package android.media;
public class AudioManager {
    public static final int MODE_NORMAL = 0;
    public static int mode;
    public int getMode() { return mode; }
}
''',
    'android/os/SystemClock.java': r'''
package android.os;
public class SystemClock {
    public static volatile long now;
    public static volatile int step = 16;
    public static volatile Runnable tick;
    private static boolean ticking;
    public static synchronized long elapsedRealtime() {
        // A callback generated by the clock observes the current arrival time without recursing.
        if (ticking) return now;
        now += step;
        if (tick != null) {
            ticking = true;
            try { tick.run(); } finally { ticking = false; }
        }
        return now;
    }
}
''',
    'android/util/Log.java': r'''
package android.util;
public class Log {
    public static final StringBuffer messages = new StringBuffer();
    public static int i(String tag, String message) { messages.append(message).append('\n'); return 0; }
    public static int e(String tag, String message, Throwable error) {
        messages.append(message).append(':').append(error).append('\n'); return 0;
    }
}
''',
    'com/stand/asr/GigaAsr.java': r'''
package com.stand.asr;
public class GigaAsr {
    public static boolean available = true;
    public static boolean ready() { return available; }
    public static byte[] received;
    public static int calls;
    public static Runnable duringDecode;
    public static String finish(byte[] pcm) {
        received = pcm; calls++;
        if (duringDecode != null) duringDecode.run();
        return "тестовая фраза";
    }
}
''',
    'com/stand/tts/TeraTts.java': r'''
package com.stand.tts;
public class TeraTts { public static void stop() {} }
''',
    'com/incall/apps/voicebase/consts/SeConst.java': r'''
package com.incall.apps.voicebase.consts;
public class SeConst {
    public static final String PARAM_WORK_MODE_VALUE_MAB = "mab", PARAM_WORK_MODE_VALUE_MAE = "mae";
}
''',
    'com/iflytek/speech/LibISSSE2.java': r'''
package com.iflytek.speech;
public class LibISSSE2 {
    public static int extractAudio(byte[] data, int length, int type, byte[] out, int size, int[] params) {
        throw new AssertionError("No JNI is allowed in this check");
    }
}
''',
    'com/incall/apps/speechassistant/se/SeSession.java': r'''
package com.incall.apps.speechassistant.se;
import com.iflytek.speech.se.PcmConvertor;
public class SeSession {
    private static final SeSession INSTANCE = new SeSession();
    public static final PcmConvertor CONVERTER = new PcmConvertor();
    public static SeSession getInstance() { return INSTANCE; }
    public byte[] processPcmData(int type, byte[] frame, int channels) {
        if (type != 4 || channels != 2 || frame.length != 7168)
            throw new AssertionError("Wrong OEM extraction arguments or truncated frame");
        return CONVERTER.processPcm(type, frame);
    }
}
''',
    'com/stand/bridge/RuBridge.java': r'''
package com.stand.bridge;
import android.util.Log;
import android.os.SystemClock;
import android.content.Context;
import com.stand.asr.GigaAsr;
public class RuBridge {
    private static final Object SESSION_LOCK = new Object();
    private static volatile RuSession ruSession;
    private static final String TAG = "RuBridge";
    private static final int TYPE_NLP = 2;
    private static String lastText;
    private static int wakeZone, ttsUntil;
    private static Context appCtx;
    private static java.util.concurrent.CountDownLatch captureDone;
    private static int injected, displayed, finished, emitted;
    private static int vadThreshold() { return Utterance.DEFAULT_RMS_THRESHOLD; }
    private static int speechMask() { return SystemClock.now < ttsUntil ? 1 : 0; }
    private static void recognizeState(RuSession session, boolean active) { session.recognizing = active; }
    private static void finishRecognize(RuSession session) { finished++; captureDone.countDown(); }
    private static String chooseQuery(String text) { return text; }
    private static void showOnScreen(String text, int type) { displayed++; }
    private static void handlePhraseZh(String text, RuSession session) { injected++; }
''' + capture + r'''
    private static void check(boolean value, String message) {
        if (!value) throw new AssertionError(message + "\n" + Log.messages);
    }
    private static void reset() {
        SystemClock.tick = null; SystemClock.now = 0; SystemClock.step = 16;
        Log.messages.setLength(0); GigaAsr.received = null; GigaAsr.duringDecode = null;
        GigaAsr.calls = 0; GigaAsr.available = true;
        injected = displayed = finished = emitted = 0; lastText = "";
        ttsUntil = 0; appCtx = new Context(); ruSession = null;
        captureDone = new java.util.concurrent.CountDownLatch(1);
        android.media.AudioManager.mode = 0;
    }
    private static void put(byte[] data, int at, int value) {
        java.nio.ByteBuffer.wrap(data).order(java.nio.ByteOrder.LITTLE_ENDIAN).putInt(at, value);
    }
    private static byte[] frame(int block) {
        byte[] data = new byte[7168];
        byte[] magic = "IFLYAUTOISS".getBytes(java.nio.charset.StandardCharsets.US_ASCII);
        System.arraycopy(magic, 0, data, 0, magic.length);
        put(data, 16, 2); put(data, 20, 7168); put(data, 24, 2);
        put(data, 64, 2); put(data, 68, 4096); put(data, 72, 512); put(data, 76, 1);
        put(data, 80, 4); put(data, 84, 512); put(data, 88, 512); put(data, 92, 1);
        if (block >= 0 && block < 8) {
            for (int at = 0; at < 512; at += 2) {
                int sample = (at % 4 == 0 ? 1 : -1) * (3000 + block * 100 + at / 2);
                data[4608 + at] = (byte) sample;
                data[4609 + at] = (byte) (sample >> 8);
            }
        }
        return data;
    }
    private static RuSession prepare() {
        reset(); ruSession = new RuSession(1); return ruSession;
    }
    private static void voiceFeed() {
        byte[] data = frame(emitted++), saved = data.clone();
        check(acceptStockFrame(data, 3584), "native SR must stay suppressed while RU owns session");
        check(java.util.Arrays.equals(saved, data), "callback mutated the OEM frame");
        java.util.Arrays.fill(data, (byte) 0); // Immediate native buffer reuse must not change worker PCM.
    }
    private static void capture(RuSession session) {
        recordSession(session);
        check(!session.recording && session.frames.isEmpty(), "native capture did not close and clear queue");
        check(finished == 1, "finish/timer cleanup missing");
    }
    private static void noCommand(String message) {
        check(GigaAsr.received == null && GigaAsr.calls == 0 && injected == 0 && displayed == 0, message);
    }
    public static void main(String[] args) throws Exception {
        reset(); check(!acceptStockFrame(null, -1), "no RU ownership must keep stock path");

        RuSession none = prepare(); SystemClock.step = 1000;
        long began = System.nanoTime(); capture(none);
        check((System.nanoTime() - began) / 1000000 < 1500, "no-frame loop exceeded bounded poll/timeout");
        check(Log.messages.toString().contains("reason=no-speech-timeout"), "no frames must time out");
        noCommand("empty capture decoded");
        check(ruSession == none && acceptStockFrame(null, -1), "finished session lost SR guard ownership");

        RuSession phrase = prepare(); SystemClock.tick = () -> voiceFeed(); capture(phrase);
        check(Log.messages.toString().contains("reason=silence-endpoint"), "speech did not end at pause");
        byte[] expected = new byte[52 * 512]; // Eight voiced 16ms frames, then 704ms of silence.
        for (int block = 0; block < 8; block++) System.arraycopy(frame(block), 4608, expected, block * 512, 512);
        check(java.util.Arrays.equals(expected, GigaAsr.received), "full-frame native PCM changed, lost or duplicated");
        check(GigaAsr.calls == 1 && injected == 1 && displayed == 1 && ruSession == phrase,
                "phrase must be delivered exactly once with continued session ownership");
        check(acceptStockFrame(null, -1) && phrase.decode, "late frame affected completed capture");

        RuSession cancelled = prepare();
        SystemClock.tick = () -> { if (emitted >= 4) stopSession(false); else voiceFeed(); };
        capture(cancelled); noCommand("capture cancellation leaked a command");
        check(ruSession == null && !acceptStockFrame(frame(0), 3584), "explicit OEM stop must release ownership");

        RuSession decoding = prepare(); SystemClock.tick = () -> voiceFeed();
        GigaAsr.duringDecode = () -> stopSession(false); capture(decoding);
        check(GigaAsr.calls == 1 && GigaAsr.received != null, "decode cancellation did not reach ASR");
        check(injected == 0 && displayed == 0 && lastText.isEmpty(), "cancelled decode leaked a command");

        RuSession stalled = prepare();
        SystemClock.tick = () -> { if (emitted < 8) voiceFeed(); else SystemClock.step = 100; };
        capture(stalled); noCommand("lost native callback after voice executed a partial phrase");
        check(stalled.recognizing && !stalled.decode && ruSession == stalled
                && Log.messages.toString().contains("reason=se-stream-stalled"),
                "voice followed by callback loss must fail closed, not become acoustic silence");

        RuSession explicit = prepare();
        SystemClock.tick = () -> { voiceFeed(); if (emitted == 16) stopSession(true); };
        capture(explicit); noCommand("explicit stop silently dropped accepted PCM and decoded a prefix");
        check(explicit.recognizing && !explicit.decode && Log.messages.toString().contains("se-stop-with-pending-frames"),
                "an unconsumed polled frame must invalidate explicit-stop decoding");
        RuSession queued = prepare(); acceptStockFrame(frame(0), 3584); stopSession(true);
        capture(queued); noCommand("explicit stop before worker silently discarded queued audio");
        check(!queued.decode && Log.messages.toString().contains("se-stop-with-pending-frames"),
                "unconsumed queue must invalidate explicit-stop decoding");

        RuSession overflow = prepare();
        for (int i = 0; i < 33; i++) check(acceptStockFrame(frame(i), 3584), "overflow fell through to native SR");
        check(overflow.frames.size() == 32 && !overflow.decode && !overflow.recording, "queue overflow was not fatal/bounded");
        stopSession(true); check(!overflow.decode, "stop(true) resurrected incomplete capture");
        capture(overflow); noCommand("overflow decoded incomplete audio");
        check(Log.messages.toString().contains("reason=se-queue-overflow") && ruSession == overflow,
                "overflow must report cause and retain ownership");

        for (int fault = 0; fault < 6; fault++) {
            RuSession invalid = prepare(); byte[] data = frame(0); int length = 3584;
            if (fault == 0) data = null;
            if (fault == 1) data = new byte[511];
            if (fault == 2) put(data, 20, 7169);
            if (fault == 3) put(data, 20, -1);
            if (fault == 4) length = 0;
            if (fault == 5) length = 7169;
            check(acceptStockFrame(data, length), "invalid envelope escaped RU ownership");
            check(!invalid.decode && !invalid.recording, "invalid envelope must fail capture");
            capture(invalid); noCommand("invalid envelope reached ASR");
        }
        for (int fault = 0; fault < 3; fault++) {
            RuSession corrupt = prepare(); byte[] data = frame(0);
            if (fault == 0) data[0] = 'X';
            if (fault == 1) put(data, 68, 10000);
            if (fault == 2) put(data, 76, 2);
            check(acceptStockFrame(data, 3584), "worker-only validation must not escape callback");
            capture(corrupt); noCommand("corrupt frame reached ASR");
            check(!corrupt.decode && Log.messages.toString().contains("reason=capture-error"),
                    "OEM extraction/format failure must disable decode");
        }

        RuSession echo = prepare(); ttsUntil = 2000; SystemClock.tick = () -> voiceFeed();
        capture(echo); noCommand("TTS echo reached ASR");
        check(Log.messages.toString().contains("reason=no-speech-timeout"), "muted capture did not time out");

        RuSession delayedEcho = prepare(); ttsUntil = 200;
        for (int i = 0; i < 20; i++) acceptStockFrame(frame(i), 3584);
        // Worker resumes after the greeting/tail; queued frames keep their original TTS state/time.
        ttsUntil = 0; SystemClock.now = 500;
        SystemClock.tick = () -> acceptStockFrame(frame(-1), 3584);
        capture(delayedEcho); noCommand("queued TTS frames were unmuted by late processing");
        check(!delayedEcho.recognizing && Log.messages.toString().contains("reason=no-speech-timeout"),
                "backlogged greeting must stay muted while fresh silence arrives");

        reset(); GigaAsr.available = false;
        check(!startSession(1) && ruSession == null, "unready ASR must retain existing startup fallback");
        reset(); android.media.AudioManager.mode = 3;
        check(!startSession(1) && ruSession == null, "call mode must retain existing startup guard");
        reset(); SystemClock.step = 1000;
        check(startSession(1), "native startup rejected without AudioRecord");
        check(captureDone.await(2, java.util.concurrent.TimeUnit.SECONDS), "native worker did not time out");
        check(ruSession != null && !ruSession.recording && Log.messages.toString().contains("source=stock-se"),
                "native worker did not preserve finished session ownership");
        noCommand("empty started worker decoded");
        System.out.println("Native capture PASS: no AudioRecord; full7168/callback3584 ownership; PCM once; pause/TTS/backlog timing; no frames; post-voice starvation; pending-stop; overflow; corrupt input; capture/decode cancellation");
    }
}
''',
}
with tempfile.TemporaryDirectory(prefix='e07-native-capture-tests-') as temporary:
    build = Path(temporary)
    sources = [root / 'src/com/stand/bridge/Utterance.java', root / 'src/com/stand/bridge/SePcm.java', oem]
    for name, content in files.items():
        path = build / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        sources.append(path)
    subprocess.run([str(java_home / 'bin/javac'), '-encoding', 'UTF-8', '-d', str(build),
                    *map(str, sources)], check=True)
    subprocess.run([str(java_home / 'bin/java'), '-cp', str(build), 'com.stand.bridge.RuBridge'],
                   check=True, timeout=20)
